### ISSUE TITLE
Can’t create an Exchange Connection for certain MFA users

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/MSCloudLoginAssistant#1]
For some reasons, this line of code never returns any session back for certain users which causes the message to let users know they exceeded the max # of connections and that they have to wait for 60 seconds indefinitely.

                       $Global:ExchangeOnlineSession = New-PSSession -Name 'ExchangeOnline' -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $O365Credential -Authentication Basic -AllowRedirection -ErrorAction SilentlyContinue

**Comment by poiriersimon** [comment]
Just created a Pull Request to leverage ADAL instead of basic Authentication . This should solve your issue since MFA disable Basic Authentication and the line you are referring to is in basic.
