### ISSUE TITLE
Login not working on Azure automation account with managed identity

### ISSUE THREAD

**Issue by steverding** [microsoft/MSCloudLoginAssistant#146]
Managed Identity Login for VMs with msi works via 

Invoke-RestMethod -Uri "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2F$($resourceEndpoint)%2F" -Headers @{Metadata = 'true' }

This throws an "unable to connect to  the remote server" error on automation accounts.

Reason is the different URL for the the Identity endpoint as described here:

https://learn.microsoft.com/en-us/azure/automation/enable-managed-identity-for-automation

This code example shows, how the endpoint has to be used on automation accounts ($env:IDENTITY_ENDPOINT is "http://127.0.0.1:20072/oauth2/token" in my account)

$resource= "?resource=https://management.azure.com/" 
$url = $env:IDENTITY_ENDPOINT + $resource 
$Headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]" 
$Headers.Add("X-IDENTITY-HEADER", $env:IDENTITY_HEADER) 
$Headers.Add("Metadata", "True") 
$accessToken = Invoke-RestMethod -Uri $url -Method 'GET' -Headers $Headers
Write-Output $accessToken.access_token

**Comment by steverding** [comment]
As an alternative, all connections can be done via powershell calls:

https://doitpsway.com/how-to-use-managed-identity-to-connect-to-azure-exchange-graph-intune-in-azure-automation-runbook

**Comment by andikrueger** [comment]
This one should be resolved by this PR #150
