### ISSUE TITLE
[Workload Tasks] Certificates are only checked in CurrentUser store

### ISSUE THREAD

**Issue by remyloy** [microsoft/MSCloudLoginAssistant#161]
The function Connect-MSCloudLoginTasksWithCertificateThumbprint only checks the CurrentUser store for the certificate with the given thumbprint, but does not check the store of the local machine.

This is problematic for us, or makes things more complicated, when used with Microsoft365DSC and the O365OrganizationSettings resource as this requires the certificate to be installed in the certificate store of the LCM user / LocalSystem user.

It would simplify things for us, if this function would use the local machine store, like the Microsoft Graph workload does, or if it at least would try both stores, if CurrentUser needs to be kept around for backwards compatibility.

**Comment by andikrueger** [comment]
In which scenario are you calling into `Connect-MSCloudLoginTasksWithCertificateThumbprint` while using Microsoft 365 DSC. Within M365DSC we use Connect-M365Tenant....

**Comment by andikrueger** [comment]
This looks like an specific issue to the Tasks Workload which was recently introduced by: https://github.com/microsoft/MSCloudLoginAssistant/commit/0c030dfe0ef8ac99c471c642e31c9d926e813197

Within Microsoft Graph, there is a better implementation available:

https://github.com/microsoft/MSCloudLoginAssistant/blob/7c806ca06ebe1d0f855fefed6aa89a56be976388/Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1#L97-L115
